import type { Metadata } from "next";
import { Kanit } from "next/font/google";

import { Sidebar } from "@/components/sidebar";

import "./globals.css";

const geistSans = Kanit({
  variable: "--font-kanit-sans",
  subsets: ["thai"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <main className="flex min-h-screen p-8">
          <Sidebar />
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
